//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSclientetelefonos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCelularesext", Namespace="http://tempuri.org/", ItemName="celularesext")]
    [System.SerializableAttribute()]
    public class ArrayOfCelularesext : System.Collections.Generic.List<WSclientetelefonos.ServiceReference1.celularesext> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="celularesext", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class celularesext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string capacidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string memoriaField;
        
        private decimal precioField;
        
        private System.Nullable<int> idmarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSclientetelefonos.ServiceReference1.marcasext marcasextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string capacidad {
            get {
                return this.capacidadField;
            }
            set {
                if ((object.ReferenceEquals(this.capacidadField, value) != true)) {
                    this.capacidadField = value;
                    this.RaisePropertyChanged("capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string memoria {
            get {
                return this.memoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.memoriaField, value) != true)) {
                    this.memoriaField = value;
                    this.RaisePropertyChanged("memoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> idmarca {
            get {
                return this.idmarcaField;
            }
            set {
                if ((this.idmarcaField.Equals(value) != true)) {
                    this.idmarcaField = value;
                    this.RaisePropertyChanged("idmarca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WSclientetelefonos.ServiceReference1.marcasext marcasext {
            get {
                return this.marcasextField;
            }
            set {
                if ((object.ReferenceEquals(this.marcasextField, value) != true)) {
                    this.marcasextField = value;
                    this.RaisePropertyChanged("marcasext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="marcasext", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class marcasext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marcaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.marcaField, value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMarcasext", Namespace="http://tempuri.org/", ItemName="marcasext")]
    [System.SerializableAttribute()]
    public class ArrayOfMarcasext : System.Collections.Generic.List<WSclientetelefonos.ServiceReference1.marcasext> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceCEL1Soap")]
    public interface WebServiceCEL1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenercelResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenercel", ReplyAction="*")]
        WSclientetelefonos.ServiceReference1.obtenercelResponse obtenercel(WSclientetelefonos.ServiceReference1.obtenercelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenercel", ReplyAction="*")]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obtenercelResponse> obtenercelAsync(WSclientetelefonos.ServiceReference1.obtenercelRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obteneridResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerid", ReplyAction="*")]
        WSclientetelefonos.ServiceReference1.obteneridResponse obtenerid(WSclientetelefonos.ServiceReference1.obteneridRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerid", ReplyAction="*")]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obteneridResponse> obteneridAsync(WSclientetelefonos.ServiceReference1.obteneridRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tel del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregar", ReplyAction="*")]
        WSclientetelefonos.ServiceReference1.agregarResponse agregar(WSclientetelefonos.ServiceReference1.agregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.agregarResponse> agregarAsync(WSclientetelefonos.ServiceReference1.agregarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenermarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenermar", ReplyAction="*")]
        WSclientetelefonos.ServiceReference1.obtenermarResponse obtenermar(WSclientetelefonos.ServiceReference1.obtenermarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenermar", ReplyAction="*")]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obtenermarResponse> obtenermarAsync(WSclientetelefonos.ServiceReference1.obtenermarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        void delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete", ReplyAction="*")]
        System.Threading.Tasks.Task deleteAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tel del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/edit", ReplyAction="*")]
        WSclientetelefonos.ServiceReference1.editResponse edit(WSclientetelefonos.ServiceReference1.editRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/edit", ReplyAction="*")]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.editResponse> editAsync(WSclientetelefonos.ServiceReference1.editRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenercelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenercel", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.obtenercelRequestBody Body;
        
        public obtenercelRequest() {
        }
        
        public obtenercelRequest(WSclientetelefonos.ServiceReference1.obtenercelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenercelRequestBody {
        
        public obtenercelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenercelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenercelResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.obtenercelResponseBody Body;
        
        public obtenercelResponse() {
        }
        
        public obtenercelResponse(WSclientetelefonos.ServiceReference1.obtenercelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenercelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSclientetelefonos.ServiceReference1.ArrayOfCelularesext obtenercelResult;
        
        public obtenercelResponseBody() {
        }
        
        public obtenercelResponseBody(WSclientetelefonos.ServiceReference1.ArrayOfCelularesext obtenercelResult) {
            this.obtenercelResult = obtenercelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obteneridRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerid", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.obteneridRequestBody Body;
        
        public obteneridRequest() {
        }
        
        public obteneridRequest(WSclientetelefonos.ServiceReference1.obteneridRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obteneridRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public obteneridRequestBody() {
        }
        
        public obteneridRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obteneridResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obteneridResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.obteneridResponseBody Body;
        
        public obteneridResponse() {
        }
        
        public obteneridResponse(WSclientetelefonos.ServiceReference1.obteneridResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obteneridResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSclientetelefonos.ServiceReference1.celularesext obteneridResult;
        
        public obteneridResponseBody() {
        }
        
        public obteneridResponseBody(WSclientetelefonos.ServiceReference1.celularesext obteneridResult) {
            this.obteneridResult = obteneridResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregar", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.agregarRequestBody Body;
        
        public agregarRequest() {
        }
        
        public agregarRequest(WSclientetelefonos.ServiceReference1.agregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class agregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSclientetelefonos.ServiceReference1.celularesext tel;
        
        public agregarRequestBody() {
        }
        
        public agregarRequestBody(WSclientetelefonos.ServiceReference1.celularesext tel) {
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="agregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.agregarResponseBody Body;
        
        public agregarResponse() {
        }
        
        public agregarResponse(WSclientetelefonos.ServiceReference1.agregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class agregarResponseBody {
        
        public agregarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenermarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenermar", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.obtenermarRequestBody Body;
        
        public obtenermarRequest() {
        }
        
        public obtenermarRequest(WSclientetelefonos.ServiceReference1.obtenermarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class obtenermarRequestBody {
        
        public obtenermarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenermarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenermarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.obtenermarResponseBody Body;
        
        public obtenermarResponse() {
        }
        
        public obtenermarResponse(WSclientetelefonos.ServiceReference1.obtenermarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenermarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSclientetelefonos.ServiceReference1.ArrayOfMarcasext obtenermarResult;
        
        public obtenermarResponseBody() {
        }
        
        public obtenermarResponseBody(WSclientetelefonos.ServiceReference1.ArrayOfMarcasext obtenermarResult) {
            this.obtenermarResult = obtenermarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="edit", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.editRequestBody Body;
        
        public editRequest() {
        }
        
        public editRequest(WSclientetelefonos.ServiceReference1.editRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class editRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSclientetelefonos.ServiceReference1.celularesext tel;
        
        public editRequestBody() {
        }
        
        public editRequestBody(WSclientetelefonos.ServiceReference1.celularesext tel) {
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSclientetelefonos.ServiceReference1.editResponseBody Body;
        
        public editResponse() {
        }
        
        public editResponse(WSclientetelefonos.ServiceReference1.editResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class editResponseBody {
        
        public editResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCEL1SoapChannel : WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCEL1SoapClient : System.ServiceModel.ClientBase<WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap>, WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap {
        
        public WebServiceCEL1SoapClient() {
        }
        
        public WebServiceCEL1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCEL1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCEL1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCEL1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSclientetelefonos.ServiceReference1.obtenercelResponse WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.obtenercel(WSclientetelefonos.ServiceReference1.obtenercelRequest request) {
            return base.Channel.obtenercel(request);
        }
        
        public WSclientetelefonos.ServiceReference1.ArrayOfCelularesext obtenercel() {
            WSclientetelefonos.ServiceReference1.obtenercelRequest inValue = new WSclientetelefonos.ServiceReference1.obtenercelRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.obtenercelRequestBody();
            WSclientetelefonos.ServiceReference1.obtenercelResponse retVal = ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).obtenercel(inValue);
            return retVal.Body.obtenercelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obtenercelResponse> WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.obtenercelAsync(WSclientetelefonos.ServiceReference1.obtenercelRequest request) {
            return base.Channel.obtenercelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obtenercelResponse> obtenercelAsync() {
            WSclientetelefonos.ServiceReference1.obtenercelRequest inValue = new WSclientetelefonos.ServiceReference1.obtenercelRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.obtenercelRequestBody();
            return ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).obtenercelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSclientetelefonos.ServiceReference1.obteneridResponse WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.obtenerid(WSclientetelefonos.ServiceReference1.obteneridRequest request) {
            return base.Channel.obtenerid(request);
        }
        
        public WSclientetelefonos.ServiceReference1.celularesext obtenerid(int id) {
            WSclientetelefonos.ServiceReference1.obteneridRequest inValue = new WSclientetelefonos.ServiceReference1.obteneridRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.obteneridRequestBody();
            inValue.Body.id = id;
            WSclientetelefonos.ServiceReference1.obteneridResponse retVal = ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).obtenerid(inValue);
            return retVal.Body.obteneridResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obteneridResponse> WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.obteneridAsync(WSclientetelefonos.ServiceReference1.obteneridRequest request) {
            return base.Channel.obteneridAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obteneridResponse> obteneridAsync(int id) {
            WSclientetelefonos.ServiceReference1.obteneridRequest inValue = new WSclientetelefonos.ServiceReference1.obteneridRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.obteneridRequestBody();
            inValue.Body.id = id;
            return ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).obteneridAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSclientetelefonos.ServiceReference1.agregarResponse WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.agregar(WSclientetelefonos.ServiceReference1.agregarRequest request) {
            return base.Channel.agregar(request);
        }
        
        public void agregar(WSclientetelefonos.ServiceReference1.celularesext tel) {
            WSclientetelefonos.ServiceReference1.agregarRequest inValue = new WSclientetelefonos.ServiceReference1.agregarRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.agregarRequestBody();
            inValue.Body.tel = tel;
            WSclientetelefonos.ServiceReference1.agregarResponse retVal = ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).agregar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.agregarResponse> WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.agregarAsync(WSclientetelefonos.ServiceReference1.agregarRequest request) {
            return base.Channel.agregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.agregarResponse> agregarAsync(WSclientetelefonos.ServiceReference1.celularesext tel) {
            WSclientetelefonos.ServiceReference1.agregarRequest inValue = new WSclientetelefonos.ServiceReference1.agregarRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.agregarRequestBody();
            inValue.Body.tel = tel;
            return ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).agregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSclientetelefonos.ServiceReference1.obtenermarResponse WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.obtenermar(WSclientetelefonos.ServiceReference1.obtenermarRequest request) {
            return base.Channel.obtenermar(request);
        }
        
        public WSclientetelefonos.ServiceReference1.ArrayOfMarcasext obtenermar() {
            WSclientetelefonos.ServiceReference1.obtenermarRequest inValue = new WSclientetelefonos.ServiceReference1.obtenermarRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.obtenermarRequestBody();
            WSclientetelefonos.ServiceReference1.obtenermarResponse retVal = ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).obtenermar(inValue);
            return retVal.Body.obtenermarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obtenermarResponse> WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.obtenermarAsync(WSclientetelefonos.ServiceReference1.obtenermarRequest request) {
            return base.Channel.obtenermarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.obtenermarResponse> obtenermarAsync() {
            WSclientetelefonos.ServiceReference1.obtenermarRequest inValue = new WSclientetelefonos.ServiceReference1.obtenermarRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.obtenermarRequestBody();
            return ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).obtenermarAsync(inValue);
        }
        
        public void delete(int id) {
            base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSclientetelefonos.ServiceReference1.editResponse WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.edit(WSclientetelefonos.ServiceReference1.editRequest request) {
            return base.Channel.edit(request);
        }
        
        public void edit(WSclientetelefonos.ServiceReference1.celularesext tel) {
            WSclientetelefonos.ServiceReference1.editRequest inValue = new WSclientetelefonos.ServiceReference1.editRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.editRequestBody();
            inValue.Body.tel = tel;
            WSclientetelefonos.ServiceReference1.editResponse retVal = ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).edit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.editResponse> WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap.editAsync(WSclientetelefonos.ServiceReference1.editRequest request) {
            return base.Channel.editAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSclientetelefonos.ServiceReference1.editResponse> editAsync(WSclientetelefonos.ServiceReference1.celularesext tel) {
            WSclientetelefonos.ServiceReference1.editRequest inValue = new WSclientetelefonos.ServiceReference1.editRequest();
            inValue.Body = new WSclientetelefonos.ServiceReference1.editRequestBody();
            inValue.Body.tel = tel;
            return ((WSclientetelefonos.ServiceReference1.WebServiceCEL1Soap)(this)).editAsync(inValue);
        }
    }
}
